version: '3.8'

services:
  # Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React (2 instances)
  frontend1:
    build: ./frontend
    environment:
      - REACT_APP_NODE_ID=frontend-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend2:
    build: ./frontend
    environment:
      - REACT_APP_NODE_ID=frontend-2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend3:
    build: ./frontend
    environment:
      - REACT_APP_NODE_ID=frontend-3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: ./backend
    volumes:
      - backend-storage:/var/www/storage
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=netumo
      - DB_USERNAME=netumo
      - DB_PASSWORD=netumo
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Queue Worker
  worker:
    build: ./backend
    command: ["php", "artisan", "queue:work"]
    depends_on:
      - backend
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=netumo
      - DB_USERNAME=netumo
      - DB_PASSWORD=netumo
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - APP_ENV=production
      - APP_KEY=base64:YOUR_APP_KEY

  # MySQL Database
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: netumo
      MYSQL_USER: netumo
      MYSQL_PASSWORD: netumo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33200:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
  redis-data:
  backend-storage: