name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Lint and test backend
        run: |
          cd backend
          composer install
          ./vendor/bin/phpunit

      - name: Lint and test frontend
        run: |
          cd frontend
          npm install
          npm run lint
          npm run test

      - name: Build and push Docker images
        run: |
          docker build -t $DOCKERHUB_USERNAME/netumo-frontend:latest ./frontend
          docker build -t $DOCKERHUB_USERNAME/netumo-backend:latest ./backend
          docker build -t $DOCKERHUB_USERNAME/netumo-worker:latest ./backend
          docker push $DOCKERHUB_USERNAME/netumo-frontend:latest
          docker push $DOCKERHUB_USERNAME/netumo-backend:latest
          docker push $DOCKERHUB_USERNAME/netumo-worker:latest

      - name: Deploy to EC2 (zero-downtime)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd /home/ec2-user/Mini-Netumo
            docker-compose pull
            docker-compose up -d --remove-orphans

      - name: Run Laravel migrations
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd /home/ec2-user/Mini-Netumo
            docker-compose exec -T backend php artisan migrate --force